# Generated by Django 4.2.11 on 2024-04-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project name')),
                ('video_file', models.FileField(upload_to='', verbose_name='Video File')),
            ],
        ),
    ]
